config/routes.rb
Rails.application.routes.draw do

  root 'leaders#new'

  post 'leaders' => 'leaders#create'

  get 'leaders' => 'leaders#index'

  get 'forum' => 'muut#index'
end

app/models/leader.rb
class Leader
  include ActiveModel::Model

  attr_accessor :name,
                :office,
                :party,
                :division,
                :twitter,
                :facebook,
                :photoUrl,
                :urls,
                :channels

  def self.all
    ObjectSpace.each_object(Leader).to_a
  end
end

app/models/voter_district.rb
class VoterDistrict
  include ActiveModel::Model

  attr_accessor(
    :address,
    :latitude,
    :longitude
  )

  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leaders_controller.rb
class LeadersController < ApplicationController

  def new
    @voter_district = VoterDistrict.new
  end

  def create
    address = params[:voter_district][:address]

    query = Rails.cache.fetch("leaders/#{address}", expires_in: 2.days) do
      RepsGetter.new(address)
    end

    if query.get.empty?
      render action: "new" and return
    end

    @parsed_address = query.parsed_address

    @leaders = query.get

    render action: "index"
  end

  def index
  end
end

app/controllers/muut_controller.rb
class MuutController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<div class="footer">
  <p>© 2015 Poliwonk, LLC.</p>
</div>

app/views/application/_header.html.erb
<div class="banner"> <div class="header-photo">
  </div>

  <div class="title-graphics">
    <svg>
      <defs>
        <filter id="dropShadow" x="-1%" y="-1%" width="120%" height="120%">
            <feMergeNode in="SourceGraphic"/>
          <feOffset in="SourceAlpha" dx="4" dy="4" result="offset"/>
          <feGaussianBlur in="offset" stdDeviation="4" result="shadow"/>
          <feGaussianBlur in="SourceGraphic" stdDeviation="1" result="blur"/>

          <feMerge>
            <feMergeNode in="shadow"/>
            <feMergeNode in="blur"/>
            <feMergeNode in="SourceGraphic"/>
          </feMerge>
        </filter>

        <filter id="glow" x="-1" y="-1" width="100" height="100">
          <feGaussianBlur stdDeviation="0 1" result="glow"/>
        </filter>
      </defs>

      <g id="poliwonk" stroke="#c7ccd1" stroke-width="2" stroke-opacity="0.2" filter="url(#dropShadow)">
        <%= render "pw_paths" %>
      </g>
    </svg>
  </div>

  <div class="gradient">
    <svg height="240px">
      <radialGradient id="pw-black" fy="70%">
        <stop offset="0%" stop-color="black" stop-opacity="0.7"/>
        <stop offset="60%" stop-color="black" stop-opacity="0.5"/>
        <stop offset="100%" stop-color="black" stop-opacity="0.2"/>
      </radialGradient>

      <rect width="100%" height="260px" fill="url(#pw-black)"/>
    </svg>
  </div>

  <div class="statement">
    <div id="slogan">
      Massive Online Democracy for the People
    </div>
  </div>
</div>

<!--div class="menu_bar">
  <ul>
    <li><#%= link_to image_tag("PW_forum.png", height: "40"), "/forum" %></li>
    <li><#%= link_to image_tag("PW_mission.png", height: "40"), "/forum#!/mission" %></
  </ul>
</div-->

app/views/application/_pw_header.html.erb
<svg>
  <defs>
    <radialGradient id="pw-black">
      <stop offset="0%" stop-color="black" stop-opacity="1.0"/>
      <stop offset="70%" stop-color="black" stop-opacity="0.7"/>
      <stop offset="100%" stop-color="#104e8b" stop-opacity="1.0"/>
    </radialGradient>

    <filter id="blur">
      <feGaussianBlur stdDeviation="5" />
    </filter>

    <mask id="pw-title">
      <rect id="alpha" x="0" y="0" width="100%" height="100%"/>

      <svg id="poliwonk" x="33%" y="20%">
        <g stroke="red" stroke-width="8" stroke-opacity="0.3">
          <%= render "pw_paths" %>
        </g>
      </svg>
    </mask>
  </defs>

  <rect id="base" x="0" y="0" width="100%" height="100%"/>
</svg>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Follow Your Leader</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Source+Sans+Pro:300", media: 'all', 'data-turbolinks-track' => true %>
        <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Open+Sans:300", media: 'all', 'data-turbolinks-track' => true %>
        <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Raleway:300,400,500,600", media: 'all', 'data-turbolinks-track' => true %>
        <!--%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Roboto:400,100', media: 'all', 'data-turbolinks-track' => true %-->
        <!--%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?sensor=false", "data-turbolinks-track" => true %-->
        <!--%= javascript_include_tag "https://apis.google.com/js/client.js?onload=load", "data-turbolinks-track" => true %-->
        <!--%#= javascript_include_tag "https://www.promisejs.org/polyfills/promise-7.0.1.min.js", "data-turbolinks-track" => true %-->
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <%= tag :meta, name: "google-api-key", content: ENV['GOOGLE_API_KEY'] %>
    </head>
    <body>
        <div class="main">
            <div class="header">
                <%= render "header" %>
            </div>

            <%= yield %>

            <%= render "footer" %>
        </div>
    </body>
</html>

app/views/leaders/_leader.html.erb
<li class='leader'>
  <div class="leader-photo">
    <%= image_tag(leader.photoUrl) %>
  </div>

  <div class="overlay">
    <div class="leader-stats">
      <ul>
        <li><%= leader.name %></li>
        <li><%= leader.office %></li>
      </ul>
    </div>
  </div>
</li>

app/views/leaders/_leader_spacer.html.erb
<div>space</div>

app/views/leaders/index.html.erb
<div class="content">
  <%= form_for VoterDistrict.new, url: leaders_path do |f| %>
    <%= f.text_field :address, placeholder: "ENTER NEW ADDRESS" %>
    <%= f.submit "REPS" %>
  <% end %> 

  <p id="officials-district">Elected Officials for <%= @parsed_address %></p>

  <ul class="leaders-list"><%= render @leaders %></ul>
</div>

app/views/leaders/new.html.erb
<div class="content">
    <p id="officials-district">Find your elected officials.</p>

    <%= form_for VoterDistrict.new, url: leaders_path do |f| %>
      <%= f.text_field :address, placeholder: "ENTER   ADDRESS" %>
      <%= f.submit "REPS" %>
    <% end %>
</div>

app/views/muut/index.html.erb
<a class="muut" href="https://muut.com/i/poliwonk/civics">poliwonk forum</a>
<script src="//cdn.muut.com/1/moot.min.js"></script>

app/views/muut/mission.html.erb
<a class="muut" href="https://muut.com/i/poliwonk/mission">poliwonk forum</a>
<script src="//cdn.muut.com/1/moot.min.js"></script>